/** \file
 *  This C source file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g
 *     -                            On : 2011-05-27 15:22:02
 *     -                 for the lexer : sLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "sLexer.h"
/* ----------------------------------------- */


/** String literals used by sLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x3C, 0x3F, 0x78, 0x6D, 0x6C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x3F, 0x3E, 0x3C, 0x6B, 0x6D, 0x6C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x3C, 0x2F, 0x6B, 0x6D, 0x6C, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x3C, 0x44, 0x6F, 0x63, 0x75, 0x6D, 0x65, 0x6E, 0x74, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x3C, 0x6E, 0x61, 0x6D, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x3C, 0x2F, 0x6E, 0x61, 0x6D, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x3C, 0x2F, 0x44, 0x6F, 0x63, 0x75, 0x6D, 0x65, 0x6E, 0x74, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x3C, 0x53, 0x74, 0x79, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x3C, 0x49, 0x63, 0x6F, 0x6E, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x3C, 0x73, 0x63, 0x61, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x3C, 0x2F, 0x73, 0x63, 0x61, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x3C, 0x49, 0x63, 0x6F, 0x6E, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x3C, 0x68, 0x72, 0x65, 0x66, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x3C, 0x2F, 0x68, 0x72, 0x65, 0x66, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x3C, 0x2F, 0x49, 0x63, 0x6F, 0x6E, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_16[]  = { 0x3C, 0x2F, 0x49, 0x63, 0x6F, 0x6E, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_17[]  = { 0x3C, 0x4C, 0x61, 0x62, 0x65, 0x6C, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_18[]  = { 0x3C, 0x63, 0x6F, 0x6C, 0x6F, 0x72, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_19[]  = { 0x3C, 0x2F, 0x63, 0x6F, 0x6C, 0x6F, 0x72, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_20[]  = { 0x3C, 0x2F, 0x4C, 0x61, 0x62, 0x65, 0x6C, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_21[]  = { 0x3C, 0x2F, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_22[]  = { 0x3C, 0x50, 0x6C, 0x61, 0x63, 0x65, 0x6D, 0x61, 0x72, 0x6B, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_23[]  = { 0x3C, 0x2F, 0x50, 0x6C, 0x61, 0x63, 0x65, 0x6D, 0x61, 0x72, 0x6B, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_24[]  = { 0x3C, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6F, 0x6E, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_25[]  = { 0x3C, 0x21, 0x5B, 0x43, 0x44, 0x41, 0x54, 0x41, 0x5B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_26[]  = { 0x5D, 0x5D, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_27[]  = { 0x3C, 0x2F, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6F, 0x6E, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_28[]  = { 0x3C, 0x73, 0x74, 0x79, 0x6C, 0x65, 0x55, 0x72, 0x6C, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_29[]  = { 0x3C, 0x2F, 0x73, 0x74, 0x79, 0x6C, 0x65, 0x55, 0x72, 0x6C, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_30[]  = { 0x3C, 0x50, 0x6F, 0x69, 0x6E, 0x74, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_31[]  = { 0x3C, 0x63, 0x6F, 0x6F, 0x72, 0x64, 0x69, 0x6E, 0x61, 0x74, 0x65, 0x73, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_32[]  = { 0x3C, 0x2F, 0x63, 0x6F, 0x6F, 0x72, 0x64, 0x69, 0x6E, 0x61, 0x74, 0x65, 0x73, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_33[]  = { 0x3C, 0x2F, 0x50, 0x6F, 0x69, 0x6E, 0x74, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_34[]  = { 0x3C, 0x2F,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   psLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  psLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->psLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->psLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__7    (psLexer ctx);
static ANTLR3_INLINE  void	mT__8    (psLexer ctx);
static ANTLR3_INLINE  void	mT__9    (psLexer ctx);
static ANTLR3_INLINE  void	mT__10    (psLexer ctx);
static ANTLR3_INLINE  void	mT__11    (psLexer ctx);
static ANTLR3_INLINE  void	mT__12    (psLexer ctx);
static ANTLR3_INLINE  void	mT__13    (psLexer ctx);
static ANTLR3_INLINE  void	mT__14    (psLexer ctx);
static ANTLR3_INLINE  void	mT__15    (psLexer ctx);
static ANTLR3_INLINE  void	mT__16    (psLexer ctx);
static ANTLR3_INLINE  void	mT__17    (psLexer ctx);
static ANTLR3_INLINE  void	mT__18    (psLexer ctx);
static ANTLR3_INLINE  void	mT__19    (psLexer ctx);
static ANTLR3_INLINE  void	mT__20    (psLexer ctx);
static ANTLR3_INLINE  void	mT__21    (psLexer ctx);
static ANTLR3_INLINE  void	mT__22    (psLexer ctx);
static ANTLR3_INLINE  void	mT__23    (psLexer ctx);
static ANTLR3_INLINE  void	mT__24    (psLexer ctx);
static ANTLR3_INLINE  void	mT__25    (psLexer ctx);
static ANTLR3_INLINE  void	mT__26    (psLexer ctx);
static ANTLR3_INLINE  void	mT__27    (psLexer ctx);
static ANTLR3_INLINE  void	mT__28    (psLexer ctx);
static ANTLR3_INLINE  void	mT__29    (psLexer ctx);
static ANTLR3_INLINE  void	mT__30    (psLexer ctx);
static ANTLR3_INLINE  void	mT__31    (psLexer ctx);
static ANTLR3_INLINE  void	mT__32    (psLexer ctx);
static ANTLR3_INLINE  void	mT__33    (psLexer ctx);
static ANTLR3_INLINE  void	mT__34    (psLexer ctx);
static ANTLR3_INLINE  void	mT__35    (psLexer ctx);
static ANTLR3_INLINE  void	mT__36    (psLexer ctx);
static ANTLR3_INLINE  void	mT__37    (psLexer ctx);
static ANTLR3_INLINE  void	mT__38    (psLexer ctx);
static ANTLR3_INLINE  void	mT__39    (psLexer ctx);
static ANTLR3_INLINE  void	mT__40    (psLexer ctx);
static ANTLR3_INLINE  void	mT__41    (psLexer ctx);
static ANTLR3_INLINE  void	mT__42    (psLexer ctx);
static ANTLR3_INLINE  void	mT__43    (psLexer ctx);
static ANTLR3_INLINE  void	mT__44    (psLexer ctx);
static ANTLR3_INLINE  void	mAL    (psLexer ctx);
static ANTLR3_INLINE  void	mNB    (psLexer ctx);
static ANTLR3_INLINE  void	mWS    (psLexer ctx);
static ANTLR3_INLINE  void	mTokens    (psLexer ctx);
static void	sLexerFree(psLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
sLexerFree  (psLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

static void
sLexerReset (psLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called sLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success psLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API psLexer sLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return sLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called sLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success psLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API psLexer sLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    psLexer ctx; // Context structure we will build and return

    ctx = (psLexer) ANTLR3_CALLOC(1, sizeof(sLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in sLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our sLexer interface
     */
    ctx->mT__7	= mT__7;
    ctx->mT__8	= mT__8;
    ctx->mT__9	= mT__9;
    ctx->mT__10	= mT__10;
    ctx->mT__11	= mT__11;
    ctx->mT__12	= mT__12;
    ctx->mT__13	= mT__13;
    ctx->mT__14	= mT__14;
    ctx->mT__15	= mT__15;
    ctx->mT__16	= mT__16;
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mT__26	= mT__26;
    ctx->mT__27	= mT__27;
    ctx->mT__28	= mT__28;
    ctx->mT__29	= mT__29;
    ctx->mT__30	= mT__30;
    ctx->mT__31	= mT__31;
    ctx->mT__32	= mT__32;
    ctx->mT__33	= mT__33;
    ctx->mT__34	= mT__34;
    ctx->mT__35	= mT__35;
    ctx->mT__36	= mT__36;
    ctx->mT__37	= mT__37;
    ctx->mT__38	= mT__38;
    ctx->mT__39	= mT__39;
    ctx->mT__40	= mT__40;
    ctx->mT__41	= mT__41;
    ctx->mT__42	= mT__42;
    ctx->mT__43	= mT__43;
    ctx->mT__44	= mT__44;
    ctx->mAL	= mAL;
    ctx->mNB	= mNB;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= sLexerFree;
    ctx->reset          = sLexerReset;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:6: ( '<?xml' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__7
 *
 * Looks to match the characters the constitute the token T__7
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__7(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__7;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:7:6: ( '<?xml' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:7:8: '<?xml'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleT__7Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__7Ex; /* Prevent compiler warnings */
    ruleT__7Ex: ;

}
// $ANTLR end T__7

//   Comes from: 8:6: ( '?><kml' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__8
 *
 * Looks to match the characters the constitute the token T__8
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__8(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__8;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:8:6: ( '?><kml' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:8:8: '?><kml'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleT__8Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__8Ex; /* Prevent compiler warnings */
    ruleT__8Ex: ;

}
// $ANTLR end T__8

//   Comes from: 9:6: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__9
 *
 * Looks to match the characters the constitute the token T__9
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__9(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__9;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:9:6: ( '>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:9:8: '>'
    {
        MATCHC('>'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__9Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__9Ex; /* Prevent compiler warnings */
    ruleT__9Ex: ;

}
// $ANTLR end T__9

//   Comes from: 10:7: ( '</kml>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__10
 *
 * Looks to match the characters the constitute the token T__10
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__10(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__10;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:10:7: ( '</kml>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:10:9: '</kml>'
    {
        MATCHS(lit_3); 
        if  (HASEXCEPTION())
        {
            goto ruleT__10Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__10Ex; /* Prevent compiler warnings */
    ruleT__10Ex: ;

}
// $ANTLR end T__10

//   Comes from: 11:7: ( '<Document>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__11
 *
 * Looks to match the characters the constitute the token T__11
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__11(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__11;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:11:7: ( '<Document>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:11:9: '<Document>'
    {
        MATCHS(lit_4); 
        if  (HASEXCEPTION())
        {
            goto ruleT__11Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__11Ex; /* Prevent compiler warnings */
    ruleT__11Ex: ;

}
// $ANTLR end T__11

//   Comes from: 12:7: ( '<name>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__12
 *
 * Looks to match the characters the constitute the token T__12
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__12(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__12;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:12:7: ( '<name>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:12:9: '<name>'
    {
        MATCHS(lit_5); 
        if  (HASEXCEPTION())
        {
            goto ruleT__12Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__12Ex; /* Prevent compiler warnings */
    ruleT__12Ex: ;

}
// $ANTLR end T__12

//   Comes from: 13:7: ( '</name>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__13
 *
 * Looks to match the characters the constitute the token T__13
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__13(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__13;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:13:7: ( '</name>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:13:9: '</name>'
    {
        MATCHS(lit_6); 
        if  (HASEXCEPTION())
        {
            goto ruleT__13Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__13Ex; /* Prevent compiler warnings */
    ruleT__13Ex: ;

}
// $ANTLR end T__13

//   Comes from: 14:7: ( '</Document>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__14
 *
 * Looks to match the characters the constitute the token T__14
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__14(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__14;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:14:7: ( '</Document>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:14:9: '</Document>'
    {
        MATCHS(lit_7); 
        if  (HASEXCEPTION())
        {
            goto ruleT__14Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__14Ex; /* Prevent compiler warnings */
    ruleT__14Ex: ;

}
// $ANTLR end T__14

//   Comes from: 15:7: ( '<Style' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__15
 *
 * Looks to match the characters the constitute the token T__15
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__15(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__15;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:15:7: ( '<Style' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:15:9: '<Style'
    {
        MATCHS(lit_8); 
        if  (HASEXCEPTION())
        {
            goto ruleT__15Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__15Ex; /* Prevent compiler warnings */
    ruleT__15Ex: ;

}
// $ANTLR end T__15

//   Comes from: 16:7: ( '<IconStyle>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__16
 *
 * Looks to match the characters the constitute the token T__16
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__16(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__16;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:16:7: ( '<IconStyle>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:16:9: '<IconStyle>'
    {
        MATCHS(lit_9); 
        if  (HASEXCEPTION())
        {
            goto ruleT__16Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__16Ex; /* Prevent compiler warnings */
    ruleT__16Ex: ;

}
// $ANTLR end T__16

//   Comes from: 17:7: ( '<scale>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:17:7: ( '<scale>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:17:9: '<scale>'
    {
        MATCHS(lit_10); 
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 18:7: ( '</scale>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:18:7: ( '</scale>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:18:9: '</scale>'
    {
        MATCHS(lit_11); 
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 19:7: ( '<Icon>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:19:7: ( '<Icon>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:19:9: '<Icon>'
    {
        MATCHS(lit_12); 
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 20:7: ( '<href>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:20:7: ( '<href>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:20:9: '<href>'
    {
        MATCHS(lit_13); 
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 21:7: ( '</href>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:21:7: ( '</href>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:21:9: '</href>'
    {
        MATCHS(lit_14); 
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 22:7: ( '</Icon>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__22;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:22:7: ( '</Icon>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:22:9: '</Icon>'
    {
        MATCHS(lit_15); 
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 23:7: ( '</IconStyle>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__23;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:23:7: ( '</IconStyle>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:23:9: '</IconStyle>'
    {
        MATCHS(lit_16); 
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 24:7: ( '<LabelStyle>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:24:7: ( '<LabelStyle>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:24:9: '<LabelStyle>'
    {
        MATCHS(lit_17); 
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 25:7: ( '<color>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:25:7: ( '<color>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:25:9: '<color>'
    {
        MATCHS(lit_18); 
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 26:7: ( '</color>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__26
 *
 * Looks to match the characters the constitute the token T__26
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__26(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__26;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:26:7: ( '</color>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:26:9: '</color>'
    {
        MATCHS(lit_19); 
        if  (HASEXCEPTION())
        {
            goto ruleT__26Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__26Ex; /* Prevent compiler warnings */
    ruleT__26Ex: ;

}
// $ANTLR end T__26

//   Comes from: 27:7: ( '</LabelStyle>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__27;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:27:7: ( '</LabelStyle>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:27:9: '</LabelStyle>'
    {
        MATCHS(lit_20); 
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 28:7: ( '</Style>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__28
 *
 * Looks to match the characters the constitute the token T__28
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__28(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__28;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:28:7: ( '</Style>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:28:9: '</Style>'
    {
        MATCHS(lit_21); 
        if  (HASEXCEPTION())
        {
            goto ruleT__28Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__28Ex; /* Prevent compiler warnings */
    ruleT__28Ex: ;

}
// $ANTLR end T__28

//   Comes from: 29:7: ( '<Placemark>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__29
 *
 * Looks to match the characters the constitute the token T__29
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__29(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__29;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:29:7: ( '<Placemark>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:29:9: '<Placemark>'
    {
        MATCHS(lit_22); 
        if  (HASEXCEPTION())
        {
            goto ruleT__29Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__29Ex; /* Prevent compiler warnings */
    ruleT__29Ex: ;

}
// $ANTLR end T__29

//   Comes from: 30:7: ( '</Placemark>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__30;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:30:7: ( '</Placemark>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:30:9: '</Placemark>'
    {
        MATCHS(lit_23); 
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 31:7: ( '<description>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__31;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:31:7: ( '<description>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:31:9: '<description>'
    {
        MATCHS(lit_24); 
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 32:7: ( '<![CDATA[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__32
 *
 * Looks to match the characters the constitute the token T__32
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__32(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__32;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:32:7: ( '<![CDATA[' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:32:9: '<![CDATA['
    {
        MATCHS(lit_25); 
        if  (HASEXCEPTION())
        {
            goto ruleT__32Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__32Ex; /* Prevent compiler warnings */
    ruleT__32Ex: ;

}
// $ANTLR end T__32

//   Comes from: 33:7: ( ']]>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__33
 *
 * Looks to match the characters the constitute the token T__33
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__33(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__33;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:33:7: ( ']]>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:33:9: ']]>'
    {
        MATCHS(lit_26); 
        if  (HASEXCEPTION())
        {
            goto ruleT__33Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__33Ex; /* Prevent compiler warnings */
    ruleT__33Ex: ;

}
// $ANTLR end T__33

//   Comes from: 34:7: ( '</description>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__34
 *
 * Looks to match the characters the constitute the token T__34
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__34(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__34;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:34:7: ( '</description>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:34:9: '</description>'
    {
        MATCHS(lit_27); 
        if  (HASEXCEPTION())
        {
            goto ruleT__34Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__34Ex; /* Prevent compiler warnings */
    ruleT__34Ex: ;

}
// $ANTLR end T__34

//   Comes from: 35:7: ( '<styleUrl>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__35
 *
 * Looks to match the characters the constitute the token T__35
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__35(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__35;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:35:7: ( '<styleUrl>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:35:9: '<styleUrl>'
    {
        MATCHS(lit_28); 
        if  (HASEXCEPTION())
        {
            goto ruleT__35Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__35Ex; /* Prevent compiler warnings */
    ruleT__35Ex: ;

}
// $ANTLR end T__35

//   Comes from: 36:7: ( '</styleUrl>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__36
 *
 * Looks to match the characters the constitute the token T__36
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__36(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__36;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:36:7: ( '</styleUrl>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:36:9: '</styleUrl>'
    {
        MATCHS(lit_29); 
        if  (HASEXCEPTION())
        {
            goto ruleT__36Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__36Ex; /* Prevent compiler warnings */
    ruleT__36Ex: ;

}
// $ANTLR end T__36

//   Comes from: 37:7: ( '<Point>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__37
 *
 * Looks to match the characters the constitute the token T__37
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__37(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__37;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:37:7: ( '<Point>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:37:9: '<Point>'
    {
        MATCHS(lit_30); 
        if  (HASEXCEPTION())
        {
            goto ruleT__37Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__37Ex; /* Prevent compiler warnings */
    ruleT__37Ex: ;

}
// $ANTLR end T__37

//   Comes from: 38:7: ( '<coordinates>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__38
 *
 * Looks to match the characters the constitute the token T__38
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__38(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__38;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:38:7: ( '<coordinates>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:38:9: '<coordinates>'
    {
        MATCHS(lit_31); 
        if  (HASEXCEPTION())
        {
            goto ruleT__38Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__38Ex; /* Prevent compiler warnings */
    ruleT__38Ex: ;

}
// $ANTLR end T__38

//   Comes from: 39:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__39
 *
 * Looks to match the characters the constitute the token T__39
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__39(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__39;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:39:7: ( ',' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:39:9: ','
    {
        MATCHC(','); 
        if  (HASEXCEPTION())
        {
            goto ruleT__39Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__39Ex; /* Prevent compiler warnings */
    ruleT__39Ex: ;

}
// $ANTLR end T__39

//   Comes from: 40:7: ( '</coordinates>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__40
 *
 * Looks to match the characters the constitute the token T__40
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__40(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__40;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:40:7: ( '</coordinates>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:40:9: '</coordinates>'
    {
        MATCHS(lit_32); 
        if  (HASEXCEPTION())
        {
            goto ruleT__40Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__40Ex; /* Prevent compiler warnings */
    ruleT__40Ex: ;

}
// $ANTLR end T__40

//   Comes from: 41:7: ( '</Point>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__41
 *
 * Looks to match the characters the constitute the token T__41
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__41(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__41;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:41:7: ( '</Point>' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:41:9: '</Point>'
    {
        MATCHS(lit_33); 
        if  (HASEXCEPTION())
        {
            goto ruleT__41Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__41Ex; /* Prevent compiler warnings */
    ruleT__41Ex: ;

}
// $ANTLR end T__41

//   Comes from: 42:7: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__42
 *
 * Looks to match the characters the constitute the token T__42
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__42(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__42;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:42:7: ( '<' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:42:9: '<'
    {
        MATCHC('<'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__42Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__42Ex; /* Prevent compiler warnings */
    ruleT__42Ex: ;

}
// $ANTLR end T__42

//   Comes from: 43:7: ( '</' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__43
 *
 * Looks to match the characters the constitute the token T__43
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__43(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__43;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:43:7: ( '</' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:43:9: '</'
    {
        MATCHS(lit_34); 
        if  (HASEXCEPTION())
        {
            goto ruleT__43Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__43Ex; /* Prevent compiler warnings */
    ruleT__43Ex: ;

}
// $ANTLR end T__43

//   Comes from: 44:7: ( '?' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__44
 *
 * Looks to match the characters the constitute the token T__44
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__44(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__44;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:44:7: ( '?' )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:44:9: '?'
    {
        MATCHC('?'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__44Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__44Ex; /* Prevent compiler warnings */
    ruleT__44Ex: ;

}
// $ANTLR end T__44

//   Comes from: 82:4: ( ( ' ' | 'a' .. 'z' | 'A' .. 'Z' | '\"' | '.' | '=' | '-' | ':' | '/' | ',' | '#' | '&' | ';' | '\\u0027' | '\\u00C0' .. '\\u00FF' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start AL
 *
 * Looks to match the characters the constitute the token AL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mAL(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = AL;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:82:4: ( ( ' ' | 'a' .. 'z' | 'A' .. 'Z' | '\"' | '.' | '=' | '-' | ':' | '/' | ',' | '#' | '&' | ';' | '\\u0027' | '\\u00C0' .. '\\u00FF' ) )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:82:6: ( ' ' | 'a' .. 'z' | 'A' .. 'Z' | '\"' | '.' | '=' | '-' | ':' | '/' | ',' | '#' | '&' | ';' | '\\u0027' | '\\u00C0' .. '\\u00FF' )
    {
        if ( LA(1) == ' ' || ((LA(1) >= '"') && (LA(1) <= '#')) || ((LA(1) >= '&') && (LA(1) <= '\'')) || ((LA(1) >= ',') && (LA(1) <= '/')) || ((LA(1) >= ':') && (LA(1) <= ';')) || LA(1) == '=' || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) || ((LA(1) >= 0x00C0) && (LA(1) <= 0x00FF)) )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleALEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleALEx; /* Prevent compiler warnings */
    ruleALEx: ;

}
// $ANTLR end AL

//   Comes from: 83:4: ( ( '-' )? ( '0' .. '9' ) ( '0' .. '9' | '.' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NB
 *
 * Looks to match the characters the constitute the token NB
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNB(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NB;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:83:4: ( ( '-' )? ( '0' .. '9' ) ( '0' .. '9' | '.' )* )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:83:6: ( '-' )? ( '0' .. '9' ) ( '0' .. '9' | '.' )*
    {

        // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:83:6: ( '-' )?
        {
            int alt1=2;
            switch ( LA(1) ) 
            {
                case '-':
                	{
                		alt1=1;
                	}
                    break;
            }

            switch (alt1) 
            {
        	case 1:
        	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:83:7: '-'
        	    {
        	        MATCHC('-'); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleNBEx;
        	        }


        	    }
        	    break;

            }
        }
        // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:83:12: ( '0' .. '9' )
        // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:83:13: '0' .. '9'
        {
            MATCHRANGE('0', '9'); 
            if  (HASEXCEPTION())
            {
                goto ruleNBEx;
            }


        }


        // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:83:22: ( '0' .. '9' | '.' )*

        for (;;)
        {
            int alt2=2;
            switch ( LA(1) ) 
            {
            case '.':
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            	{
            		alt2=1;
            	}
                break;

            }

            switch (alt2) 
            {
        	case 1:
        	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:
        	    {
        	        if ( LA(1) == '.' || ((LA(1) >= '0') && (LA(1) <= '9')) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleNBEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop2;	/* break out of the loop */
        	    break;
            }
        }
        loop2: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleNBEx; /* Prevent compiler warnings */
    ruleNBEx: ;

}
// $ANTLR end NB

//   Comes from: 84:4: ( ( '\\t' | '\\r' | '\\n' | '\\u000C' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;
       
    
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:84:4: ( ( '\\t' | '\\r' | '\\n' | '\\u000C' )+ )
    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:84:6: ( '\\t' | '\\r' | '\\n' | '\\u000C' )+
    {
        // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:84:6: ( '\\t' | '\\r' | '\\n' | '\\u000C' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) ) 
        	{
        	case '\t':
        	case '\n':
        	case '\f':
        	case '\r':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3) 
        	{
        	    case 1:
        	        // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || ((LA(1) >= '\f') && (LA(1) <= '\r')) )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }
        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(psLexer ctx)
{
    {
        //  /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:8: ( T__7 | T__8 | T__9 | T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | AL | NB | WS )
        
        ANTLR3_UINT32 alt4;

        alt4=41;

        switch ( LA(1) ) 
        {
        case '<':
        	{
        		switch ( LA(2) ) 
        		{
        		case '?':
        			{
        				alt4=1;
        			}
        		    break;
        		case '/':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'k':
        					{
        						alt4=4;
        					}
        				    break;
        				case 'n':
        					{
        						alt4=7;
        					}
        				    break;
        				case 'D':
        					{
        						alt4=8;
        					}
        				    break;
        				case 's':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'c':
        							{
        								alt4=12;
        							}
        						    break;
        						case 't':
        							{
        								alt4=30;
        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 4;
        						    EXCEPTION->state        = 30;


        						    goto ruleTokensEx;
        						}

        					}
        				    break;
        				case 'h':
        					{
        						alt4=15;
        					}
        				    break;
        				case 'I':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'c':
        							{
        								switch ( LA(5) ) 
        								{
        								case 'o':
        									{
        										switch ( LA(6) ) 
        										{
        										case 'n':
        											{
        												switch ( LA(7) ) 
        												{
        												case '>':
        													{
        														alt4=16;
        													}
        												    break;
        												case 'S':
        													{
        														alt4=17;
        													}
        												    break;

        												default:
        												    CONSTRUCTEX();
        												    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        												    EXCEPTION->message      = (void *)"";
        												    EXCEPTION->decisionNum  = 4;
        												    EXCEPTION->state        = 58;


        												    goto ruleTokensEx;
        												}

        											}
        										    break;

        										default:
        										    CONSTRUCTEX();
        										    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        										    EXCEPTION->message      = (void *)"";
        										    EXCEPTION->decisionNum  = 4;
        										    EXCEPTION->state        = 54;


        										    goto ruleTokensEx;
        										}

        									}
        								    break;

        								default:
        								    CONSTRUCTEX();
        								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        								    EXCEPTION->message      = (void *)"";
        								    EXCEPTION->decisionNum  = 4;
        								    EXCEPTION->state        = 47;


        								    goto ruleTokensEx;
        								}

        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 4;
        						    EXCEPTION->state        = 32;


        						    goto ruleTokensEx;
        						}

        					}
        				    break;
        				case 'c':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'o':
        							{
        								switch ( LA(5) ) 
        								{
        								case 'l':
        									{
        										alt4=20;
        									}
        								    break;
        								case 'o':
        									{
        										alt4=34;
        									}
        								    break;

        								default:
        								    CONSTRUCTEX();
        								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        								    EXCEPTION->message      = (void *)"";
        								    EXCEPTION->decisionNum  = 4;
        								    EXCEPTION->state        = 48;


        								    goto ruleTokensEx;
        								}

        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 4;
        						    EXCEPTION->state        = 33;


        						    goto ruleTokensEx;
        						}

        					}
        				    break;
        				case 'L':
        					{
        						alt4=21;
        					}
        				    break;
        				case 'S':
        					{
        						alt4=22;
        					}
        				    break;
        				case 'P':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'l':
        							{
        								alt4=24;
        							}
        						    break;
        						case 'o':
        							{
        								alt4=35;
        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 4;
        						    EXCEPTION->state        = 36;


        						    goto ruleTokensEx;
        						}

        					}
        				    break;
        				case 'd':
        					{
        						alt4=28;
        					}
        				    break;

        				default:
        				    alt4=37;}

        			}
        		    break;
        		case 'D':
        			{
        				alt4=5;
        			}
        		    break;
        		case 'n':
        			{
        				alt4=6;
        			}
        		    break;
        		case 'S':
        			{
        				alt4=9;
        			}
        		    break;
        		case 'I':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'c':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'o':
        							{
        								switch ( LA(5) ) 
        								{
        								case 'n':
        									{
        										switch ( LA(6) ) 
        										{
        										case 'S':
        											{
        												alt4=10;
        											}
        										    break;
        										case '>':
        											{
        												alt4=13;
        											}
        										    break;

        										default:
        										    CONSTRUCTEX();
        										    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        										    EXCEPTION->message      = (void *)"";
        										    EXCEPTION->decisionNum  = 4;
        										    EXCEPTION->state        = 57;


        										    goto ruleTokensEx;
        										}

        									}
        								    break;

        								default:
        								    CONSTRUCTEX();
        								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        								    EXCEPTION->message      = (void *)"";
        								    EXCEPTION->decisionNum  = 4;
        								    EXCEPTION->state        = 51;


        								    goto ruleTokensEx;
        								}

        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 4;
        						    EXCEPTION->state        = 39;


        						    goto ruleTokensEx;
        						}

        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 4;
        				    EXCEPTION->state        = 15;


        				    goto ruleTokensEx;
        				}

        			}
        		    break;
        		case 's':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'c':
        					{
        						alt4=11;
        					}
        				    break;
        				case 't':
        					{
        						alt4=29;
        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 4;
        				    EXCEPTION->state        = 16;


        				    goto ruleTokensEx;
        				}

        			}
        		    break;
        		case 'h':
        			{
        				alt4=14;
        			}
        		    break;
        		case 'L':
        			{
        				alt4=18;
        			}
        		    break;
        		case 'c':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'o':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'l':
        							{
        								alt4=19;
        							}
        						    break;
        						case 'o':
        							{
        								alt4=32;
        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 4;
        						    EXCEPTION->state        = 42;


        						    goto ruleTokensEx;
        						}

        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 4;
        				    EXCEPTION->state        = 19;


        				    goto ruleTokensEx;
        				}

        			}
        		    break;
        		case 'P':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'l':
        					{
        						alt4=23;
        					}
        				    break;
        				case 'o':
        					{
        						alt4=31;
        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 4;
        				    EXCEPTION->state        = 20;


        				    goto ruleTokensEx;
        				}

        			}
        		    break;
        		case 'd':
        			{
        				alt4=25;
        			}
        		    break;
        		case '!':
        			{
        				alt4=26;
        			}
        		    break;

        		default:
        		    alt4=36;}

        	}
            break;
        case '?':
        	{
        		switch ( LA(2) ) 
        		{
        		case '>':
        			{
        				alt4=2;
        			}
        		    break;

        		default:
        		    alt4=38;}

        	}
            break;
        case '>':
        	{
        		alt4=3;
        	}
            break;
        case ']':
        	{
        		alt4=27;
        	}
            break;
        case ',':
        	{
        		alt4=33;
        	}
            break;
        case '-':
        	{
        		switch ( LA(2) ) 
        		{
        		case '0':
        		case '1':
        		case '2':
        		case '3':
        		case '4':
        		case '5':
        		case '6':
        		case '7':
        		case '8':
        		case '9':
        			{
        				alt4=40;
        			}
        		    break;

        		default:
        		    alt4=39;}

        	}
            break;
        case ' ':
        case '"':
        case '#':
        case '&':
        case '\'':
        case '.':
        case '/':
        case ':':
        case ';':
        case '=':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
        case 0x00C0:
        case 0x00C1:
        case 0x00C2:
        case 0x00C3:
        case 0x00C4:
        case 0x00C5:
        case 0x00C6:
        case 0x00C7:
        case 0x00C8:
        case 0x00C9:
        case 0x00CA:
        case 0x00CB:
        case 0x00CC:
        case 0x00CD:
        case 0x00CE:
        case 0x00CF:
        case 0x00D0:
        case 0x00D1:
        case 0x00D2:
        case 0x00D3:
        case 0x00D4:
        case 0x00D5:
        case 0x00D6:
        case 0x00D7:
        case 0x00D8:
        case 0x00D9:
        case 0x00DA:
        case 0x00DB:
        case 0x00DC:
        case 0x00DD:
        case 0x00DE:
        case 0x00DF:
        case 0x00E0:
        case 0x00E1:
        case 0x00E2:
        case 0x00E3:
        case 0x00E4:
        case 0x00E5:
        case 0x00E6:
        case 0x00E7:
        case 0x00E8:
        case 0x00E9:
        case 0x00EA:
        case 0x00EB:
        case 0x00EC:
        case 0x00ED:
        case 0x00EE:
        case 0x00EF:
        case 0x00F0:
        case 0x00F1:
        case 0x00F2:
        case 0x00F3:
        case 0x00F4:
        case 0x00F5:
        case 0x00F6:
        case 0x00F7:
        case 0x00F8:
        case 0x00F9:
        case 0x00FA:
        case 0x00FB:
        case 0x00FC:
        case 0x00FD:
        case 0x00FE:
        case 0x00FF:
        	{
        		alt4=39;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt4=40;
        	}
            break;
        case '\t':
        case '\n':
        case '\f':
        case '\r':
        	{
        		alt4=41;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 4;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;
        }

        switch (alt4) 
        {
    	case 1:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:10: T__7
    	    {
    	        /* 1:10: T__7 */
    	        mT__7(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:15: T__8
    	    {
    	        /* 1:15: T__8 */
    	        mT__8(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:20: T__9
    	    {
    	        /* 1:20: T__9 */
    	        mT__9(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:25: T__10
    	    {
    	        /* 1:25: T__10 */
    	        mT__10(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:31: T__11
    	    {
    	        /* 1:31: T__11 */
    	        mT__11(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:37: T__12
    	    {
    	        /* 1:37: T__12 */
    	        mT__12(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:43: T__13
    	    {
    	        /* 1:43: T__13 */
    	        mT__13(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:49: T__14
    	    {
    	        /* 1:49: T__14 */
    	        mT__14(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:55: T__15
    	    {
    	        /* 1:55: T__15 */
    	        mT__15(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:61: T__16
    	    {
    	        /* 1:61: T__16 */
    	        mT__16(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:67: T__17
    	    {
    	        /* 1:67: T__17 */
    	        mT__17(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:73: T__18
    	    {
    	        /* 1:73: T__18 */
    	        mT__18(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:79: T__19
    	    {
    	        /* 1:79: T__19 */
    	        mT__19(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:85: T__20
    	    {
    	        /* 1:85: T__20 */
    	        mT__20(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:91: T__21
    	    {
    	        /* 1:91: T__21 */
    	        mT__21(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:97: T__22
    	    {
    	        /* 1:97: T__22 */
    	        mT__22(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:103: T__23
    	    {
    	        /* 1:103: T__23 */
    	        mT__23(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:109: T__24
    	    {
    	        /* 1:109: T__24 */
    	        mT__24(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:115: T__25
    	    {
    	        /* 1:115: T__25 */
    	        mT__25(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:121: T__26
    	    {
    	        /* 1:121: T__26 */
    	        mT__26(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:127: T__27
    	    {
    	        /* 1:127: T__27 */
    	        mT__27(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 22:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:133: T__28
    	    {
    	        /* 1:133: T__28 */
    	        mT__28(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 23:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:139: T__29
    	    {
    	        /* 1:139: T__29 */
    	        mT__29(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 24:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:145: T__30
    	    {
    	        /* 1:145: T__30 */
    	        mT__30(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 25:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:151: T__31
    	    {
    	        /* 1:151: T__31 */
    	        mT__31(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 26:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:157: T__32
    	    {
    	        /* 1:157: T__32 */
    	        mT__32(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 27:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:163: T__33
    	    {
    	        /* 1:163: T__33 */
    	        mT__33(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 28:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:169: T__34
    	    {
    	        /* 1:169: T__34 */
    	        mT__34(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 29:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:175: T__35
    	    {
    	        /* 1:175: T__35 */
    	        mT__35(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 30:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:181: T__36
    	    {
    	        /* 1:181: T__36 */
    	        mT__36(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 31:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:187: T__37
    	    {
    	        /* 1:187: T__37 */
    	        mT__37(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 32:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:193: T__38
    	    {
    	        /* 1:193: T__38 */
    	        mT__38(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 33:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:199: T__39
    	    {
    	        /* 1:199: T__39 */
    	        mT__39(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 34:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:205: T__40
    	    {
    	        /* 1:205: T__40 */
    	        mT__40(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 35:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:211: T__41
    	    {
    	        /* 1:211: T__41 */
    	        mT__41(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 36:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:217: T__42
    	    {
    	        /* 1:217: T__42 */
    	        mT__42(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 37:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:223: T__43
    	    {
    	        /* 1:223: T__43 */
    	        mT__43(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 38:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:229: T__44
    	    {
    	        /* 1:229: T__44 */
    	        mT__44(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 39:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:235: AL
    	    {
    	        /* 1:235: AL */
    	        mAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 40:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:238: NB
    	    {
    	        /* 1:238: NB */
    	        mNB(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 41:
    	    // /etudiant/jerome.audoux/Téléchargements/ANTLR2/s.g:1:241: WS
    	    {
    	        /* 1:241: WS */
    	        mWS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
